74 create crud api route for products backend
AdrianDanlos/Data-Management-App pull request #78
Opened 2023-05-19 16:56 UTC by JoelEncinas

2023-05-19 17:44 UTC, AdrianDanlos requested changes
Lots of nice changes 🔥 🚀

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +      if (products.length > 1) {
What are we checking for here? Shouldn't this be `products.length > 0` instead?

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    if (products) {
We can probably simplify this if-else statement to something like:

```
if (products?.length > 0) {
  res.status(200).json(products);
}

res.status(404).json({ message: "No products found" });
```

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    res.status(500).json({ error: "Internal server error" });
For transparency and debugging purposes is it possible here to send the actual error thrown by the server instead of "Internal server error".

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    const id = req.params.id;
This is perfectly fine, but if you want to look like a 10x dev you can do: `const {id} = req.params;` so you avoid repeating "id" twice.

Feel free to change other instances in the code with the same pattern: `const id = req.params.id`.

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    res.status(500).json({ error: "Internal server error", errMessage: err });
`errMessage: err` -> this is what I was talking about in my previous comment

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    } else {
`else` not needed here. We can simply do `res.status(404).json({ message: "No product found with that ID" });`. after the `if` statement.

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    const { name, description, price } = req.body;
10x dev

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    } else {
No need for `else` here either.

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +      { new: true }
What is the purpose of this? Just curious.

2023-05-19 17:44 UTC, AdrianDanlos commented on backend/src/controllers/productController.ts
> +    } else {
`else` not needed here either

2023-05-19 18:28 UTC, JoelEncinas commented on backend/src/controllers/productController.ts
> +    res.status(500).json({ error: "Internal server error" });
yep, will implement as middleware in future update. the logging the actual err was done for debugging

2023-05-19 18:29 UTC, JoelEncinas commented on backend/src/controllers/productController.ts
> +    const id = req.params.id;
wouldnt' it be more readable if there is only 1 parameter?

2023-05-19 18:30 UTC, JoelEncinas commented on backend/src/controllers/productController.ts
> +    } else {
true

2023-05-19 18:31 UTC, JoelEncinas commented on backend/src/controllers/productController.ts
> +      { new: true }
returns the object with updated data so you could send the data back updated

2023-05-19 18:32 UTC, JoelEncinas commented on backend/src/controllers/productController.ts
> +    if (products) {
looks better

2023-05-22 12:06 UTC, AdrianDanlos submitted a review, later dismissed

2023-05-22 12:07 UTC, AdrianDanlos approved these changes
LGTM

2023-05-22 12:07 UTC, merged